### ISSUE TITLE
Monitoring check: Cloud Load-Balancer

### ISSUE THREAD

**Issue by siso** [boxidau/rax-autoscaler#11]

**Comment by jon-walton** [comment]
http://docs.rackspace.com/loadbalancers/api/v1.0/clb-devguide/content/GET_showCurrentUsage_v1.0__account__loadbalancers__loadBalancerId__usage_current_Usage_Reports-d1e3009.html#GET_showCurrentUsage_v1.0__account__loadbalancers__loadBalancerId__usage_current_Usage_Reports-d1e3009-Request

```
{
"links": [],
"loadBalancerUsageRecords": [
{
"id": 42030,
"startTime": "2014-06-25T15:00:00-05:00",
"endTime": "2014-06-25T16:00:00-05:00",
"outgoingTransfer": 0,
"incomingTransfer": 0,
"outgoingTransferSsl": 0,
"incomingTransferSsl": 0,
"numVips": 1,
"vipType": "PUBLIC",
"averageNumConnections": 0,
"averageNumConnectionsSsl": 0,
"numPolls": 0,
"sslMode": "OFF"
}
]
}
```

**Comment by Teddy-Schmitz** [comment]
This is in the plugins branch.
