### ISSUE TITLE
Make --as-group a positional arg

### ISSUE THREAD

**Issue by boxidau** [boxidau/rax-autoscaler#36]
No point doing --as-group, lets just have the AS group name as the first arg

**Comment by boxidau** [comment]
group name configuration should be dynamically detected in the following ways
- Check if there's only one group, use it if there is
- Check instance metadata for key "ras-group"
- Failover to trying to work out what group the instance is a member of by walking groups

**Comment by Teddy-Schmitz** [comment]
So do you want to get rid of this parameter completely then?  Or will the whole flow be.
- If group is defined as argument use that
- Check if there's only one group, use it if there is
- Check instance metadata for key "ras-group"
- Failover to trying to work out what group the instance is a member of by walking groups

**Comment by boxidau** [comment]
After discussion we are going with name parsing on hostnames. Autoscale group members have naming conventions which can be followed for config options.

for example app-server-1234567890 could be an as group server name

we should remove the random string and see if the remainder is a config section name, the replaces the "expensive" walking of AS group members and also the metadata method
