### ISSUE TITLE
Performance enhancement for getting cloud monitoring metrics

### ISSUE THREAD

**Issue by boxidau** [boxidau/rax-autoscaler#4]
Single threaded operation is quite slow when gathering statistics.

Potential solution: spawn threads for each entity so metrics may be gathered in parallel

**Comment by siso** [comment]
Would you scale in/out depending on multiple metrics?

**Comment by boxidau** [comment]
Probably not. I'm referring to gathering metrics for each node in the AS group

**Comment by boxidau** [comment]
We should also think about putting an upper limit on the number of nodes to gather data from. Since we are calculating an average across the cluster. For example if there are 100 nodes in the AS group we can probably just sample the metric on 10 of them and still make an informed decision as to whether to scale, any more is just a waste of resources and API calls.

**Comment by boxidau** [comment]
@siso: As discussed we will just use the --max-sample cmd arg instead of threading
