### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by Teddy-Schmitz** [boxidau/rax-autoscaler#76]
Create a plugin system to allow people to write their own checks to determine scale ups and scale downs.

**Comment by siso** [comment]
http://stevedore.readthedocs.org/en/latest/essays/pycon2013.html#why-use-plugins
https://pypi.python.org/pypi/Plugins/

**Comment by jon-walton** [comment]
initial code push in c36cfa5b9e028c52a4627ee1ac5e7f1b9f06c3e1

I haven't figured out how to get the namespace created without doing a `python setup.py install` and `pip uninstall rax-autoscaler` (the uninstall cleans up your environment for running locally. I found that if I had it installed, I was debugging against the installed version)

If you don't do that, you'll get an exception about no plugins found for `raxas.ext`

this is a breaking change with regards to the data sent with the webhooks, webhook tests currently fail.

the plugin architecture is also a breaking change with config.json

**Comment by siso** [comment]
Hey @jon-walton, I haven't tried yet, but according to the [documentation](http://stevedore.readthedocs.org/en/latest/tutorial/creating_plugins.html#registering-the-plugins) it is the expected behaviour:
- install raxas with `python setup.py install`
- Setuptools creates Metadata in EGG-INFO
-  plugins are now discoverable

**Comment by jon-walton** [comment]
ok cool. after uninstalling, it still leaves the egg-info in the project's directory so it works. I haven't looked into setup.py much so I'm wondering if theres another way to get the egg-info folder there without doing a full install.

**Comment by jon-walton** [comment]
ready for review in commit 23c8426

**Comment by jon-walton** [comment]
closed by b8bd5e8ce364ccc04e3afe41d5156922313a4647
