### ISSUE TITLE
pre/post commands

### ISSUE THREAD

**Issue by siso** [boxidau/rax-autoscaler#8]
Implement pre-cmd and post-cmd, to be executed before and after triggering webhooks.

Merge from AsPOC

**Comment by siso** [comment]
This can be used, for instance, to notify New Relic that a node has been deleted

**Comment by boxidau** [comment]
Should this be a webhook call with a POST rather than a command execution?

**Comment by boxidau** [comment]
Blocked by #32

**Comment by boxidau** [comment]
http://stackoverflow.com/questions/3290522/urllib2-and-json
