### ISSUE TITLE
Checking monitoring checks should be in its own module

### ISSUE THREAD

**Issue by Teddy-Schmitz** [boxidau/rax-autoscaler#88]
We shouldn't have all the check code in autoscale.py.  It should just be calling the module that runs that type of check.

**Comment by siso** [comment]
Hey @Teddy-Schmitz, from my understanding this is a duplicate of #76 ?
Are you thinking of something different?

**Comment by Teddy-Schmitz** [comment]
Yep, it's the same, closing.
